services:
  backend:
    container_name: oct_ai_go_backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  frontend:
    container_name: oct_ai_go_frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - nms:/app/node_modules

volumes:
  nms:
